### ISSUE TITLE
Aggregate query support ?

### ISSUE THREAD

**Issue by xensystems** [tzmfreedom/go-soapforce#3]
Hi tzmfreedom!

Here is the query:
```
SELECT Owner.name Owner, COUNT(Id) Number FROM Account WHERE ... GROUP BY Owner.name ORDER BY COUNT(Id)
```

it is successfully executed. I'm getting a bunch of record in a result, like this:

```
&soapforce.SObject{
  Type: "AggregateResult",
  FieldsToNull: nil,
  Id: "",
  Fields: map[string]interface {}{
    "Owner": "John Doe",
  },
}
```

But how do I get Number field ?

**Comment by tzmfreedom** [comment]
@xensystems Thank you for reporting !
It didn't support aggregating query and I add support it now, version `v0.1.1` !
#4 

Would you try to use it now?

**Comment by xensystems** [comment]
It works, thank you!
